// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PomodoroFocus.Data;

#nullable disable

namespace PomodoroFocus.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250731171449_AddDefaultStr")]
    partial class AddDefaultStr
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("PomodoroFocus.Models.PomodoroSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActualBreakDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActualWorkDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("LLMSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlannedBreakDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlannedWorkDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserInput")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
